<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFHjfj29\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFHjfj29/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFHjfj29.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFHjfj29\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFHjfj29\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FHjfj29',
    'container.build_id' => '88f2667d',
    'container.build_time' => 1520937634,
));
