<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMi2dZY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMi2dZY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOMi2dZY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOMi2dZY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOMi2dZY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OMi2dZY',
    'container.build_id' => '16f5907d',
    'container.build_time' => 1520932455,
));
