<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8LYVST\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8LYVST/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL8LYVST.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL8LYVST\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerL8LYVST\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'L8LYVST',
    'container.build_id' => '6ceaca3a',
    'container.build_time' => 1520873347,
));
